name: "Discord Message Notify"
description: "Send a message to a Discord channel using a webhook"
author: "Bo-Yi Wu"
inputs:
  webhook_id:
    description: "The ID of the Discord webhook"
    required: true
  webhook_token:
    description: "The token of the Discord webhook"
    required: true
  message:
    description: "The content of the message to send (up to 2000 characters)"
  file:
    description: "The content of the file to send"
  color:
    description: "The color code for the embed message"
  wait:
    description: "Wait for server confirmation before responding, and return the created message body"
  tts:
    description: "Set to true if the message should be read aloud using text-to-speech"
  username:
    description: "Override the default username of the webhook"
  avatar_url:
    description: "Override the default avatar of the webhook"
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "message-square"
  color: "gray-dark"
